# Generated by Django 3.2.8 on 2021-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_json', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
