# Generated by Django 3.2.8 on 2021-10-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=254)),
                ('product_url', models.CharField(max_length=254)),
                ('product_image_url', models.CharField(max_length=254)),
                ('product_rating', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_json', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
