# Generated by Django 3.2.8 on 2021-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_url',
            field=models.CharField(blank=True, default='None', max_length=254, null=True),
        ),
    ]
