# Generated by Django 3.2.8 on 2021-10-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_products_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=254)),
                ('main_Seller', models.BooleanField(null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_json', models.TextField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='home.products')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
