# Generated by Django 3.2.8 on 2021-10-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_price',
        ),
    ]
