# Generated by Django 3.2.8 on 2021-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_main_seller_offers_main_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
